import { ROLES } from "./roles.js";

export const PERMISSIONS = Object.freeze({
  PROFILE_READ_SELF: "profile:read:self",
  PROFILE_UPDATE_SELF: "profile:update:self",
  USER_READ_ANY: "user:read:any",
  USER_ROLE_UPDATE_ANY: "user:role:update:any",
  CATEGORY_CREATE: "category:create",
  POST_CREATE: "post:create",
  POST_READ_OWN: "post:read:own",
  POST_READ_ANY: "post:read:any",
  POST_UPDATE_OWN: "post:update:own",
  POST_UPDATE_ANY: "post:update:any",
  POST_DELETE_OWN: "post:delete:own",
  POST_DELETE_ANY: "post:delete:any",
  COMMENT_CREATE: "comment:create",
  COMMENT_DELETE_OWN: "comment:delete:own",
  COMMENT_DELETE_ANY: "comment:delete:any",
});

const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.USER]: Object.freeze([
    PERMISSIONS.PROFILE_READ_SELF,
    PERMISSIONS.PROFILE_UPDATE_SELF,
    PERMISSIONS.POST_CREATE,
    PERMISSIONS.POST_READ_OWN,
    PERMISSIONS.POST_UPDATE_OWN,
    PERMISSIONS.POST_DELETE_OWN,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.COMMENT_DELETE_OWN,
  ]),
  [ROLES.MODERATOR]: Object.freeze([
    PERMISSIONS.PROFILE_READ_SELF,
    PERMISSIONS.PROFILE_UPDATE_SELF,
    PERMISSIONS.POST_CREATE,
    PERMISSIONS.POST_READ_OWN,
    PERMISSIONS.POST_READ_ANY,
    PERMISSIONS.POST_UPDATE_OWN,
    PERMISSIONS.POST_DELETE_OWN,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.COMMENT_DELETE_OWN,
    PERMISSIONS.COMMENT_DELETE_ANY,
  ]),
  [ROLES.ADMIN]: Object.freeze([
    PERMISSIONS.PROFILE_READ_SELF,
    PERMISSIONS.PROFILE_UPDATE_SELF,
    PERMISSIONS.USER_READ_ANY,
    PERMISSIONS.USER_ROLE_UPDATE_ANY,
    PERMISSIONS.CATEGORY_CREATE,
    PERMISSIONS.POST_CREATE,
    PERMISSIONS.POST_READ_OWN,
    PERMISSIONS.POST_READ_ANY,
    PERMISSIONS.POST_UPDATE_OWN,
    PERMISSIONS.POST_UPDATE_ANY,
    PERMISSIONS.POST_DELETE_OWN,
    PERMISSIONS.POST_DELETE_ANY,
    PERMISSIONS.COMMENT_CREATE,
    PERMISSIONS.COMMENT_DELETE_OWN,
    PERMISSIONS.COMMENT_DELETE_ANY,
  ]),
});

export function permissionsForRole(role) {
  return ROLE_PERMISSIONS[role] || [];
}

export function can(role, permission) {
  return permissionsForRole(role).includes(permission);
}
